version: "3.8"
services:
  messaging-service:
    build: .
    container_name: messaging-service
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  redis_data:
  

